Improve preprocessing: add `yandex-team.com` domain
epam/OSCI pull request #97
Opened 2021-09-03 16:34 UTC by nslsrv

Process `yandex-team.ru` and `yandex-team.com` as valid Yandex domains while calculating OSCI.

2021-09-04 05:57 UTC, vlad-isayko requested changes
Thanks for your input. Please add another industry field in accordance with the new paragraph https://github.com/epam/OSCI#how-can-i-add-a-company-which-is-missing-from-the-osci-ranking
Do not forget to also change the version in the file
https://github.com/epam/OSCI/blob/f2f739a6a3f39fadff2cad0b28037f5215875764/osci/__init__.py#L1, in accordance with the rules described here https://github.com/epam/OSCI#osci-versioning-newspaper

2021-09-04 09:28 UTC, nslsrv commented
> Please add another industry field in accordance with the new paragraph https://github.com/epam/OSCI#how-can-i-add-a-company-which-is-missing-from-the-osci-ranking

Thanks for the reply! I think I might use your advice on how to correctly specify an industy field:
- Are multiple industries allowed? It can be hard to describe a corporation's activity with only one.
- Even if choosing only one, should I choose only from the industries listed [in the document](https://github.com/epam/OSCI#how-can-i-add-a-company-which-is-missing-from-the-osci-ranking)? "Other" option makes an impression that the list is not comprehensive. Maybe some other publicly available classification exists that could be used?

2021-09-07 21:46 UTC, cm-howard commented
Thanks for the comments @nslsrv regarding industries. 👍🏼 

We'd encourage all contributing organisations to pick **just one primary industry**; this is as we hope to be able to present future views around industry and organisations possessing multiple industries will potentially distort these views.

Additionally, the range of industries we've chosen are derived from similar Open Source reports and industry analyst groupings such as those used by Gartner. We streamlined the list to the current set we have but of course welcome further suggestions.

I hope the above provides some further details on our process/way of working.

2021-09-08 03:18 UTC, vlad-isayko approved these changes

2021-09-08 03:18 UTC, merged